name: Checkmarx SAST Scan
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Checkmarx Action
      uses: checkmarx-ts/checkmarx-github-action@v1.0.6
      with:
        cxServer: https://software-ag.checkmarx.net
        cxToken: 014DF517-39D1-4453-B7B3-9930C563627C
        cxTeam: \CxServer\SP\Checkmarx\SAG
